---
- hosts: local
  remote_user: deploy
  tasks:
  - name: zhao {zhao_test} update web server (--exclude-file)
    synchronize: src=/home/deploy/zhaoyong/ dest=/data/zhaoyong/ rsync_opts=--delete,--exclude-from=/data/ansible/public/excludefile
