---
- hosts: web
  remote_user: deploy
  tasks:
  - name: piaotai {ticket_order} update web server (--exclude-file)
    synchronize: src=/home/deploy/piaowu_v2/ticket_order/  dest=/data/web/ticket_order/ rsync_opts=--delete,--exclude-from=/data/ansible/public/excludefile
