---
- hosts: web
  remote_user: deploy
  tasks:
  - name: piaotai {ticket_manage} update web server (--exclude-file)
    synchronize: src=/home/deploy/piaowu_v2/ticket_manage/ dest=/data/web/ticket_manage/ rsync_opts=--delete,--exclude-from=/data/ansible/public/excludefile
