---
- hosts: web
  remote_user: deploy
  tasks:
  - name: piaotai {ticket_supply} update web server (--exclude-file)
    synchronize: src=/home/deploy/piaowu_v2/ticket_supply/ dest=/data/web/ticket_supply/ rsync_opts=--delete,--exclude-from=/data/ansible/public/excludefile
