---
- hosts: web
  remote_user: deploy
  tasks:
  - name: piaotai {ticket_organization} update web server (--exclude-file)
    synchronize: src=/home/deploy/piaowu_v2/ticket_organization/ dest=/data/web/ticket_organization/ rsync_opts=--delete,--exclude-from=/data/ansible/public/excludefile
