---
- hosts: web
  remote_user: deploy
  tasks:
  - name: piaotai {ticket_info} update web server (--exclude-file)
    synchronize: src=/home/deploy/piaowu_v2/ticket_info/   dest=/data/web/ticket_info/  rsync_opts=--delete,--exclude-from=/data/ansible/public/excludefile
