---
- hosts: web
  remote_user: deploy
  tasks:
  - name: piaotai {ticket_organization} update web server (--exclude-file)
    synchronize: src=/home/deploy/piaowu_v2/ticket_organization/ dest=/data/web/ticket_organization/ rsync_opts=--delete,--exclude-from=/data/ansible/public/excludefile
  - name: piaotai {ticket_scenic} update web server (--exclude-file)
    synchronize: src=/home/deploy/piaowu_v2/ticket_scenic/ dest=/data/web/ticket_scenic/ rsync_opts=--delete,--exclude-from=/data/ansible/public/excludefile
  - name: piaotai {ticket_info} update web server (--exclude-file)
    synchronize: src=/home/deploy/piaowu_v2/ticket_info/   dest=/data/web/ticket_info/  rsync_opts=--delete,--exclude-from=/data/ansible/public/excludefile
  - name: piaotai {ticket_order} update web server (--exclude-file)
    synchronize: src=/home/deploy/piaowu_v2/ticket_order/  dest=/data/web/ticket_order/ rsync_opts=--delete,--exclude-from=/data/ansible/public/excludefile
  - name: piaotai {ticket_supply} update web server (--exclude-file)
    synchronize: src=/home/deploy/piaowu_v2/ticket_supply/ dest=/data/web/ticket_supply/ rsync_opts=--delete,--exclude-from=/data/ansible/public/excludefile
  - name: piaotai {ticket_manage} update web server (--exclude-file)
    synchronize: src=/home/deploy/piaowu_v2/ticket_manage/ dest=/data/web/ticket_manage/ rsync_opts=--delete,--exclude-from=/data/ansible/public/excludefile
  - name: piaotai {ticket_agency} update web server (--exclude-file)
    synchronize: src=/home/deploy/piaowu_v2/ticket_agency/ dest=/data/web/ticket_agency/ rsync_opts=--delete,--exclude-from=/data/ansible/public/excludefile
  - name: piaotai {ticket_admin} update web server 
    synchronize: src=/home/deploy/piaowu_v2/ticket_admin/ dest=/data/web/ticket_admin/ rsync_opts=--delete
