---
- hosts: web
  remote_user: deploy
  tasks:
  - name: piaotai {openapi_supply} update web server (--exclude-file)
    synchronize: src=/home/deploy/openapi_supply/ dest=/data/web/openapi_supply/ rsync_opts=--delete
