---
- hosts: web
  remote_user: deploy
  tasks:
  - name: piaotai {openapi_ticket} update web server (--exclude-file)
    synchronize: src=/home/deploy/openapi_ticket/ dest=/data/web/openapi_ticket/ rsync_opts=--delete,--exclude-from=/data/ansible/public/excludefile
