---
- hosts: web
  remote_user: deploy
  tasks:
  - name: teamtour {teamtour_company} update web server (--exclude-file,--delete)
    synchronize: src=/home/deploy/teamtour_company/ dest=/data/web/teamtour_company/ rsync_opts=--exclude-from=/data/ansible/teamtour/exclude_teamtour/exclude_teamtour_company,--delete
