---
- hosts: web
  remote_user: deploy
  tasks:
  - name: teamtour {teamtour_agency} update web server (--exclude-file,--delete)
    synchronize: src=/home/deploy/teamtour_agency/ dest=/data/web/teamtour_agency/ rsync_opts=--exclude-from=/data/ansible/teamtour/exclude_teamtour/exclude_teamtour_agency,--delete
