---
- hosts: web
  remote_user: deploy
  tasks:
  - name: teamtour {teamtour_api} update web server (--exclude-file,--delete)
    synchronize: src=/home/deploy/teamtour_api/ dest=/data/web/teamtour_api/ rsync_opts=--exclude-from=/data/ansible/teamtour/exclude_teamtour/exclude_teamtour_api,--delete
