---
- hosts: local
  remote_user: deploy
  tasks:
  - name: gan update local server (--exclude-file)
    synchronize: src=/home/deploy/gan/ dest=/data/gan/ rsync_opts=--delete,--exclude-from=/data/ansible/public/excludefile
