---
- hosts: 192.168.1.53
  remote_user: deploy
  tasks:
  - name: Change Status
    shell: mv /data/web/setting/ticket_local.php /data/web/setting/ticket_local.php.online
  - name: Offline
    shell: mv /data/web/setting/ticket_local.php.offline /data/web/setting/ticket_local.php
